# Generated by Django 4.1.7 on 2023-05-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservarhora',
            old_name='rut_pac',
            new_name='rut',
        ),
    ]
