# Generated by Django 4.1.7 on 2023-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificarPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecuperarContraseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('contraseña_nueva', models.CharField(max_length=30)),
                ('confirmar_contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='confirmarreserva',
            name='apellidos_pac',
            field=models.CharField(max_length=50, null=True, verbose_name='Apelldos Paciente'),
        ),
        migrations.AddField(
            model_name='confirmarreserva',
            name='nombre_pac',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento de usuario'),
        ),
    ]
