# Generated by Django 4.1.7 on 2023-04-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='id_rec',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Id reclamo'),
        ),
    ]
