# Generated by Django 4.1.7 on 2023-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='id_user',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Id usuario'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='id_tipo_usuario',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
