# Generated by Django 4.1.7 on 2023-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registrousuario_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='id_tipo_usuario',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
