# Generated by Django 4.1.7 on 2023-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rut_pac_reservarhora_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservarhora',
            old_name='id_prev',
            new_name='prevision',
        ),
    ]
