# Generated by Django 4.1.7 on 2023-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tipousuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='id_reclamo',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Id reclamo'),
        ),
    ]
